# Generated by Django 2.1.7 on 2019-05-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=30),
        ),
    ]
