# Generated by Django 2.1.7 on 2019-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0003_auto_20190523_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
