# Generated by Django 2.1.7 on 2019-05-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0004_auto_20190523_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pista',
            name='ruta',
            field=models.CharField(max_length=300),
        ),
    ]
