# Generated by Django 2.1.7 on 2019-05-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0005_auto_20190523_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
