# Generated by Django 2.2.1 on 2019-08-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0010_auto_20190804_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='acuerdoAsociado',
        ),
    ]
