# Generated by Django 2.2.1 on 2019-08-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0013_auto_20190804_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='acuerdoAsociado',
        ),
    ]
