# Generated by Django 2.2.1 on 2019-08-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal_app', '0014_remove_trabajador_acuerdoasociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='acuerdoAsociado',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='principal_app.Acuerdo'),
        ),
    ]
